# Request
geometry_msgs/PoseWithCovarianceStamped initial_pose  # Initial pose of the drone

---
# Response
bool success                       # True if setting initial pose succeeded
string message                     # Optional error or success message
